src/modules-lua/noit/module/http.lua
* Fix the string concatenation with an invalid header
=> fix(remote.http): invalid www-authenticate header

docs/config/modules/noit.module.cloudwatch.xml, src/modules-lua/noit/AWSClient.lua, src/modules-lua/noit/module/cloudwatch.lua
Added support for signing AWS Requests with Signature Version 4.
=> Added support for signing AWS Requests with Signature Version 4.

src/noit_check_resolver.c
We were using 0 as a sentinel value to indicate that we had not yet
determined the TTL from a received DNS response. This is broken, because
0 is a valid TTL, which we're supposed to interpret to mean that the
DNS response should not be cached. Fix this part of the resolver by
using -1 as the sentinel value.
=> Better handling of TTL 0 in DNS responses.

src/Makefile.in, src/modules-lua/ffi_libnoit.lua, src/modules/noit_lua_noit_binding.c, src/noit_message_decoder.c, src/noit_metric.h, src/noit_metric_director.c, src/noit_metric_director.h, src/noit_metric_rollup.c, src/noit_metric_rollup.h
renamed metric_id_t -> noit_metric_id_t
Pushing noit_metric_message_t.value as lightuserdata so that the data mapping can be done via ffi_libnoit.lua
=> Implemented noit_metric_rollup

src/modules/httptrap.c
Every time we get into the HttpTrap callback, force looking up the check
by the uuid. This will prevent us from trying to use a stale check
pointer.
=> Force Check Lookup In HttpTrap Callback

src/modules/lua_check.c, src/noit_check.c, src/noit_check.h
Add support for NP_SUPPRESS_METRICS.
Add support for setting and unsetting check flags.
=> Support .immediate_metric to use stats_log_immediate_metric.

src/modules/noit_lua_noit_binding.c, src/noit_metric.h, src/noit_metric_director.c, src/noit_metric_director.h
Added reference counting into noit_metric_director to make sure we
handle memory properly.
=> Add Reference Counts To Fix Memory Leaks In noit_metric_director

src/modules/httptrap.c
Note truncation errors in the successful response.
Use mtev_json to correctly output JSON responses.
=> Make httptrap truncate metric names to 255 and continue.

src/noit_check.c
hence we couldn't see the metrics dispatched via noit_stats_log_immediate_metric in /checks/show/account_<X>/<UUID>
=> noit_stats_log_immediate_metric didn't add the metric to the global metric table

src/noit_filters.c, src/noit_filters.h, src/noit_filters_rest.c
This allows the UI to push rulesets with a seq tag in it. We'll need these for a clustered noit soon.
=> added optional seq to filtersets

src/stratcon_jlog_streamer.c
If the users specifies as CN when deleting, we should sweep
all noits (one) with the CN regardless of address.  When we add
a noit, if CN is specified, we should ensure no other registered
noit has that CN.  When we initiate connections we should use the
CN if available so as not to start duplicate sessions to common
target addresses (particular to mtev_reverse connections that have
a blank target).
=> Leverage CN better when adding/deleting noits.

src/modules/noit_lua_noit_binding.c, src/modules/selfcheck.c, src/noit_metric_director.c, src/noit_metric_director.h
Added two atomics couning incoming and outgoing messages in metric_director
=> Monitoring message stream in metric_director

src/modules/httptrap.c, src/modules/ping_icmp.c, src/noit_check.c, src/noit_conf_checks.c, src/noit_metric_director.c, src/stratcon_realtime_http.c
This should be more efficient.
=> Switch uuid_copy To mtev_uuid_copy

src/modules/lua_check.c
We were building a new resume info, which creates a thread.
Then we were calling new_coro which creates a thread on top of it.
This would cause the first thread to remain referenced and leak.
=> Don't lose a lua thread on each invocation.

src/modules/dns.c
We were casualy about creating timeouts for DNS checks.  The check
would fire on some thread and create a timeout on that thread which
could be different from the thread managing the DNS server connection
socket.  This could cause races where DNS completect while the timeout
was firing and vice versa.  By making the timeouts fire on the same
thread that owns the socket, we avoid this race condition.
=> Ensure timeouts in DNS checks are thread-local to DNS fds.

src/modules/ssh2.c
We were always setting the connection timeout to 10ms, which is wrong.
The logic for checking the timeout was busted. Fix to store the actual
timeout data in the check's info struct and use that.
=> Fix Bug In SSH2 Check Connection Timeout

src/Makefile.dep, src/noit_message_decoder.c, src/noit_message_decoder.h, src/noit_metric.c, src/noit_metric.h, src/noit_metric_director.c, src/noit_websocket_handler.c
* Adopt tagset stuff from aidan with mild API variance.
* enforce tag size limits
=> Extend the metric decoding to extract stream and measurement tags.

src/noit_websocket_handler.c
If we get into a send to a websocket and determine that there are no
metrics to send, send a "heartbeat" message - the other end may be
depending on regular messages across the connection to function, and
this will allow it to act.
=> Send Heartbeat Messages To Websocket If No Metrics To Send

src/Makefile.in, src/noit_metric_tag_search.c, src/noit_metric_tag_search.h
* API for string -> AST
* sample implementation of matching an AST against a single tagset.
=> API for constructing 'complex' tag matching criteria

src/noit_check.c, src/noit_clustering.c
=> Announce cluster identity in notice channel

src/noit_filters.c
This allows us to move replicated filtersets to a sub-node.
=> Introduce replication_prefix attribute for filtersets

src/stratcon_datastore.c
Rather than using the default back queue, use a dedicated job queue with
a configurable concurrency to push stratcon data.
=> Add Dedicated Stratcon Datastore Push Job Queue

src/noit_metric.h, src/noit_metric_private.h
=> expose noit_metric_tags_canonical

src/Makefile.in
Right now this is just noit_b2sm but there may eventually be more.
Fixes #446
=> Tools-only install target

src/noit_metric_director.c
Fixes stream tags fallout in caql-broker
=> Use metric name with tags to lookup interest

src/modules-lua/noit/module/smtp.lua
=> Proxy protocol smtp

src/modules/ping_icmp.c
In multi-threaded situations, we might find that someone is in the
timeout event in another thread when we try to remove it (which
will fail) and we should let them take care of business.
=> Make sure we've removed the timeout event before we destroy it.

buildtools/docker.sh, src/modules/Makefile.in, src/modules/graphite.c, src/modules/graphite.xml
This is pending larger testing (haggar) putting up for review now for approach.
=> Graphite check

src/modules/graphite.c
Clients can connect to the listener over TLS with a SNI hostname
<uuid>-<secret>[.some.fqdn] and it will be mapped back to the
appropriate internal graphite check if one exists.  This is
multi-tenancy without a port orgy.
=> Support a regular mtev_listener for graphite and respect SNI.

src/noit_check.c
... since those will be readded as well now.
=> Set readd flag to noit_poller_schedule also for deleted checks

src/modules/httptrap.c, src/noit_filters.c
* filter at reception time to track filtered count.
* add execution and denied counts to filtersets.
=> HTTPTrap should note filtered.

src/modules-lua/noit.lua, src/modules-lua/noit/module/haproxy.lua, src/modules-lua/noit/module/http.lua, src/modules-lua/noit/module/imap.lua, src/modules-lua/noit/module/monit.lua, src/modules-lua/noit/module/nginx.lua, src/modules-lua/noit/module/pop3.lua, src/modules-lua/noit/module/resmon.lua, src/modules-lua/noit/module/smtp.lua, src/modules-lua/noit/module/tcp.lua, src/noit_check_tools.h
* Improve check->thread distribution
* Cache the common mtev.conf_get_string calls in modules.
=> Fix startup speed for large configs.

src/Makefile.in, src/modules/noit_lua_libnoit_binding.c, src/modules/noit_lua_noit_binding.c, src/noit_metric_director.c
This PR adds instrumentation to noit_metric_director, based on mtev_stats / libcircmetrics.
Some functions that exposed similar statistics are removed.
=> CIRC-4693 Add Instrumentation

src/noit_check.c
=> Setting the cluster is unsafe during check reading.

src/noit_check.c
* true -> use it
* false -> don't use it
* absent -> use it if you've already got it
=> Make the use_lmdb config attributed for checks kind to upgrades.

src/noit_check_lmdb.c, src/noit_filters_lmdb.c, test/busted/lua-support/reconnoiter.lua, test/busted/simple/load/load_spec.lua
Handle checks failing to load more cleanly and add additional testing to
validate that this all works properly.
=> CIRC-4638 - Check Error Handling And Testing

src/noit_metric_director.c
With this change mtev stats will contain the following entries:
```
$ curl -s 'localhost:8081/mtev/stats.json?format=simple' | jq '.noit'
{
"metric_director": {
"distributed": 3578,
"delivered": 32009,
"queued": 32181,
"seen": 3845,
"dropped": {
"too_full": 0,
"too_late": 0
}
}
}
```
```
$ curl -s 'localhost:8081/mtev/stats.json?format=tagged' | jq '.' | grep dropped
"dropped|ST[app:noit,reason:too_full,subsystem:metric_director,units:messages]": {
"dropped|ST[app:noit,reason:too_late,subsystem:metric_director,units:messages]": {
```
The tag reason:too_full/too_late was used, so that the meaning is more clear to the operator.
Dropped reason:threshold/backlogged would be more consistent with the variable names,
but confusing to people not familiar with the code.
=> noit_metric_director: Separate counts for threshold/backlog

src/noit_conf_checks_lmdb.c
If a check name is passed in instead of a UUID, look for it in the
running checks and return it if found.
=> CIRC-4638 - Fix Console Show Check By Name

src/modules/noit_lua_libnoit_binding.c
We were copying a reference to the stack.  Instead copy it
to the heap and free it later.
=> msg.id.ctags: fix use of stack after return.

src/modules/histogram.c, test/busted/checks_data/httptrap/httptrap_spec.lua
* `{ "metric": { "_type": "[hH]", "_value": "<b64encoded hist>" } }`
=> Support base64 encoded histograms a string values.

src/stratcon_datastore.c
If the noit was removed while there was a datastore payload in-flight,
we attempted to complete the event which has been closed due to
disconnection.  Keep a reference to avoid use-after-free and check to
make sure the event has not been closed before adding/triggering it.
=> Fix crash removing noit with in-flight submission.

src/noit_metric_tag_search.c, src/noit_metric_tag_search.h
Split the free method into reset and free
https://circonus.atlassian.net/browse/CIRC-5983
=> CIRC-5983 - Split Free into Reset and Free

src/flatbuffers/metric.fbs, src/flatbuffers/metric_batch.fbs, src/flatbuffers/metric_common.fbs, src/flatbuffers/metric_list.fbs, src/noit_check_log.c, src/noit_check_log_helpers.c, src/noit_fb.c, src/noit_fb.h
Let us change this to be tighter before we start using it.
=> Change the metric encoding to a tuple list.

src/stratcon_iep.c
Audit all calls and fix incorrect inputs
- https://circonus.atlassian.net/browse/CIRC-6125
- All tests pass
-
=> CIRC-6125 - Audit inet_ntop

src/noit_metric_tag_search.c, test/test_tags.c
* Fix uninitialized graphite regex when no regex is found.
* Fix several leaks.
=> Fix memory issues with tag search.

src/modules/snmp.c, src/modules/snmp.xml
Reverts circonus-labs/reconnoiter#690
=> Revert "Add a setting to SNMP checks to control the max PDU size"

src/modules/snmp.c, src/modules/snmp.xml
Redo of the SNMP batched mode to fix fetch bugs.
=> fix snmp v2c batched mode OID filling and reqid assignment

.gitignore, src/noit_metric_director.c
Remove the need for an additional zero valued uuid
https://circonus.atlassian.net/browse/CIRC-6349
=> CIRC-6349 - Remove the need for an additional zero valued uuid 

src/noit_check.c, test/busted/cluster/checkconfig/checkconfig_spec.lua
We should be using xmlNewTextChild, not xmlNewChild.
=> Fix entity encoding of check config XML generated.

src/noit_check_rest.c, src/noit_filters_rest.c
Fix underflow by removing unneeded code
=> CIRC-6895 - Underflow

src/noit_check.c
Fix improper use of mtev safe allocator
=> CIRC-6898 - Heap Usafe After Free

src/modules/histogram.c, src/modules/httptrap.c, src/modules/lua_check.c, src/modules/ping_icmp.c, src/modules/reverse_check.c, src/modules/snmp.c, src/modules/statsd.c, src/noit_check.c, src/noit_check.h, src/noit_check_lmdb.c, src/noit_check_rest.c, src/noit_check_tools.c, src/noit_clustering.c, src/noit_conf_checks.c, src/noit_conf_checks_lmdb.c, src/noit_socket_listener.c
- Fix some misuses of mtev SMR
- Fix a couple of eventer_t leaks
- Fix race condition on de-schedule that leads
to heap use after free
- typo
=> CIRC-6912 - SMR Fixes

src/noit_check.c, src/noit_conf_checks.c
Fix a few issues with check reference counting.
=> CIRC-6987 - Fix Some Check Reference Counts

src/modules/snmp.c
Fix reference count usage in snmp checks
- Jira [report](https://circonus.atlassian.net/browse/CIRC-6990)
=> CIRC-6990 - SNMP Ref Counts

src/noit_filters_lmdb.c
Free is inside the inner for loop, will cause rule to be used
post free
=> CIRC-7005 - Double Free

src/modules/lua_check.c, src/modules/ping_icmp.c, src/modules/selfcheck.c, src/noit_check.c, src/noit_check_tools.c
=> CIRC-7007 - Missing SMR Transactions

src/modules/check_test.c, src/modules/graphite.cpp, src/modules/httptrap.c, src/modules/opentsdb.c, src/modules/statsd.c, src/noit_check.c, src/noit_websocket_handler.c
=> CIRC-7008 - Missing SMR Transactions

src/modules/httptrap.c, src/noit_websocket_handler.c
=> CIRC-7010 - Missing mtev_memory_end Calls

src/modules/snmp.c
=> CIRC-7013 - Add Missing SMR Transaction

src/modules/collectd.c, src/modules/dns.c, src/modules/example/example.c, src/modules/external.c, src/modules/ganglia.c, src/modules/httptrap.c, src/modules/lua_check.c, src/modules/ping_icmp.c, src/modules/prometheus.c, src/modules/selfcheck.c, src/modules/snmp.c, src/modules/statsd.c, src/noit_check.c, src/noit_socket_listener.c
Add SMR transactions to Lua API
=> CIRC-7014 - Add Missing SMR Transactions

src/noit_check.c, src/noit_check_lmdb.c
- Introduce more assertions for missing SMR tx
- Fix subsequent assertion failures
=> CIRC-7015 - More SMR TX

src/modules/ganglia.c, src/modules/selfcheck.c
- Transaction started too late
- Add missing end transactions
=> CIRC-7022 - SMR Transaction Fixes

src/modules/check_test.c, src/modules/httptrap.c, src/noit_check.c, src/noit_check.h, src/noit_check_lmdb.c, src/noit_check_log.c, src/noit_check_rest.c, src/noit_conf_checks.c
- Fix race conditions when accessing the check's stat array pointers
- Add more assertions for SMR transactions
- Fix new assertion failures
=> CIRC-7024 - Race Conditions

src/noit_check.c
Remove duplicate begin and end transaction
=> CIRC-7025 - Missing End Tx

src/noit_conf_checks.c
=> CIRC-7030 - Missing SMR Transaction

src/modules/dns.c
Add SMR transaction to DNS module
=> CIRC-7031 - DNS Missing SMR Tx

src/modules/ganglia.c, src/modules/lua_check.c, src/noit_check_log.c, src/noit_metric_director.c, src/noit_metric_tag_search.c
=> CIRC-7034 - Missing mtev_memory_end

src/modules/httptrap.c
=> CIRC-7035 - Missing SMR transaction

src/modules/check_test.c, src/modules/httptrap.c, src/modules/lua_check.c, src/noit_check.c
- Bad shifts
- Negative array indexes
- More assertions for mtev_memory
=> CIRC-7044 - UBSan

src/modules/collectd.c
=> CIRC-7058 - Add missing SMR transaction

src/noit_metric.c, src/noit_metric.h, test/test_tags.c
=> CIRC-6730 - Stack overflow

src/noit_metric_tag_search.c, test/test_tags.c
and(foo:/) should exact match / and not be a regex.
=> Fix naked / tag search.

src/noit_check.c
=> CIRC-7114 - Missing SMR Transaction

src/noit_check.c
=> CIRC-7115 - Missing SMR transactions

LICENSE, pkg/debian/noit.install
Also remove jar from debian pkg list.
=> Remove Log4j from license declaration

src/modules/check_test.c, src/modules/dns.c, src/modules/histogram.c, src/modules/lua_check.c, src/noit_check.c, src/noit_check_lmdb.c, src/noit_check_log_helpers.c, src/stratcon_ingest.c, src/stratcon_realtime_http.c
All gone. Replaced with malloc/calloc. Some logic simplified.
=> CIRC-6131 Remove Alloca from Reconnoiter

src/noit_metric_tag_search.c
A graphite-style tag search could have thousands of `{opt1,opt2,opt3}`
expansion internals making the search expression very long while
preserving a reasonable final matching tag cat or name. We should allow
the AST to parse them arbitrarily long.
=> Tag searches can be (much) longer than tags.

src/noit_metric_tag_search.c
=> Make tag search arguments arrays grow geometrically.

src/modules/prometheus.c
=> Support prometheus fanout per request on a single check

test/test_tags.c
Add test to flip two elements in an AST and verify that everything is
correct afterwards.
=> Add Test To Swap Tag Order In Search Tree

src/modules/prometheus.c
Call mtev_memory_safe_free and let mtev_memory_safe_malloc_cleanup
call metric_local_free
=> CIRC-8268 - Brokers ingesting Prometheus data OOM regularly

src/noit_metric.h
No need to break the ABI, we don't have to
=> CIRC-8354 - ABI fix

src/stratcon_jlog_streamer.c
=> Avoid double free of broker CN on deletion.

src/modules/httptrap.c, src/modules/otlphttp.cpp, src/modules/prometheus.c, src/noit_check.c, src/noit_socket_listener.c
Fix memory leak introduced by fixing double free
=> CIRC-8828 - memory leak

src/noit_metric_tag_search.c
Cache pcre_study results to avoid heap contention
=> CIRC-8835 - watchdog pcre_study

src/Makefile.in
Will be used to enhance crash reporting.
=> CIRC-9095 Add mtev version to noit.env

src/noit_check_lmdb.c, src/noitd.c
* Remove debug message
* Add comment
=> Small Code Cleanup

src/modules/httptrap.c
This reverts commit 9affa5657ec9797964b4f22d47ca9ee90c20d338.
=> Revert "Fix Computed Value When Only One Value Present (#836)"

src/modules/httptrap.c
If someone submits and unusually large payload to httptrap, we could potentially watchdog if we don't yield back to the eventer loop.
Add an artificial limit to check every now and then if the thread has been in a read loop for too long; if it has, yield control back.
=> Don't Allow httptrap Module To Read For Too Long

src/modules/httptrap.c
Check to see if we have anything to flush in ACO in the httptrap check. If we don't, don't bother offloading the operation to the jobq.
=> Only Use ACO And Jobq If Needed In Httptrap

test/busted/checks_data/httptrap/httptrap_spec.lua
Need to have a test check with a much longer period to test data accumulation.
=> Fix Inconsistent httptrap Test

buildtools/el7/env.inc
update path to fix pickletools linkage issue when running cnfigure.sh
=> CIRC-10199 - fix el7 configure PATH.

src/noit_metric_director.c
Update the usage of the kafka hooks for libmtev 2.7.7
=> Updated Kafka Hooks

src/noit_check_lmdb.c
Fix some instances where we were leaking keys on LMDB seeks.
=> Fix LMDB Check Memory Leaks

.gitignore, src/Makefile.in, src/modules/Makefile.in, src/modules/prometheus.c, src/noit_metric_director.c, src/noit_metric_director.h, src/noit_prometheus_translation.c, src/noit_prometheus_translation.h, src/proto/prometheus.proto, src/proto/prometheus_types.proto
First pass at adding support to noit_metric_director for handling prometheus-formatted data coming in from kafka message queues.
=> Prometheus/Kafka Support In noit_metric_director
