circonus-labs/reconnoiter

pkg/debian/noit.install, pkg/debian/rules, pkg/debian/stratcon.install, trusty-snmp-c.patch
I have created the attached patch-set so that the reconnoiter packages will build on more modern Debian based distributions like Ubuntu 14.04 and Debian 7. 
The trusty-snmp-c.patch is intended to be applied to the dpkg source package net-snmp and create a separate package "libsnmpclient-c" so that entire SNMP stacks do not need to be installed on the noit servers. I have tested this patch on several vanilla amazon Debian and ubuntu instances to confirm that it works. I have deliberately kept the patch separate so that the patch does not pollute the vanilla snmp-c.patch which  you supply (and that works on all systems). I hope that fits with your conventions?
A few other bugs have been fixed in the Debian scripts so that they follow what is outlined in the "BUILDING" README file (i.e. the …
=> bugfix debian install scripts to work on ubuntu 14.04

pkg/debian/control
This PR only changes the pkg/debian/control file. It improves the dependencies so that all of the available functionality is available for reconnoiter. It assumes that the custom net-snmp patch has been applied and the Concurrency-Kit package is built and installed. At this point there is no FQ iep driver available.
=> Updated debian control file.

src/modules-lua/noit/module/ssh2.lua
We're already reading the banner; would be nice to have it as a metric.
=> Add SSH banner as a metric in the lua ssh2 check

src/modules/histogram_impl.c, src/modules/histogram_impl.h
This clarifies which method actually changes the histogram and allows to pass const histograms more easily.
=> defined histo pointers as const if possible and added hist_serialize_b64

src/modules/handoff_ingestor.c, src/modules/postgres_ingestor.c, src/stratcon_datastore.c, src/stratcon_datastore.h, src/stratcon_ingest.c, src/stratcon_ingest.h
Add a parameter, "sweeping", to stratcon ingestion functions. This will
allow us to differentiate between files that we're receiving via JLOG
and files that we find via a sweep when stratcon starts up.
=> Add "sweeping" Parameter To Stratcon Ingestion

src/modules-lua/noit/module/http.lua
Fixes an infinite loop in relative redirects that do not contain the correct number of parents:
```
get_absolute_path('/hello/../../signin') --> "/signin"
```
This fix returns the same URI that cURL returns.
=> http: fix infinite loop in get_absolute_uri

src/modules/histogram_impl.c
The bucket boundary should be given by the formula: ```(hb.val * 10) * 10^(hb.exp)```
In the boundary case that the computed `hb.val == 100`, we need to absorb the excess
power of 10 into the exponent, by _increasing_ it's value by one.
This is only possible if `hb.exp < 127`. if `hb.exp == 127` the value lies outside of the
histogram range, in which case we return NaN.
=> Fixed edge case in historam bucket computation.

src/modules-lua/noit/HttpClient.lua
HEAD requests are trying to fetch a body. This PR checks for that instance and bails early.
=> fix: ignore body on HEAD request

src/js/noit-connection/noit-connection.js
same as in noit-connection.js portion of nad pr#56
* add setTimeout to reverse socket
* add a watchdog (checking last times for rx/tx) for edge cases
* add retries with drift for re-establishing remote connection
* add extra debugging messages
* remove redundant require of util as sys
* try to push all connection/communications abnormalities through socket.end() to centralize handling of exceptions
=> changes to support reconnecting, retrying, better callback error handling, and more debugging messages

src/modules-lua/noit/module/jezebel.lua, src/modules/noit_lua_snmp.c
Two changes:
* Only load lua_snmp if there's a jezebel snmp lua module defined
* Lock around the lua_snmp initialization to make sure that multiple
threads don't call it at once, make sure that we only init once
=> Make Lua SNMP Loading Safer

src/noit_check_rest.c
was using `strlen(fullpath)` where `sizeof(fullpath)` was intended.
fixed.
=> fix `make_conf_path`'s null-termination of local `fullpath` variable.

src/noit_check.c
If a check is passive, recycle it unless it's either:
* Flagged as running for some reason (shouldn't happen)
or....
* Last ran (period*2) seconds ago
This will prevent freeing a check that's in-flight and causing possible
memory errors.
=> Fix So We Don't Have A Use-After-Free On Passive Checks

src/modules/histogram.c
We were freeing the contents of the histotier object, but not the object
itself. Free it.
=> Free Histotier Object When Done With It

src/modules/dns.c, src/modules/external.c, src/modules/fq_driver.c, src/modules/handoff_ingestor.c, src/modules/ip_acl.c, src/modules/lua_check.c, src/modules/mysql.c, src/modules/snmp.c, src/noit_check.c, src/noit_check_resolver.c, src/noit_check_tools_shared.c, src/noit_conf_checks.c, src/noit_filters.c, src/noit_jlog_listener.c, src/noit_module.c, src/stratcon_iep.c, src/stratcon_jlog_streamer.c, src/stratcon_realtime_http.c
Rather than initializing to MTEV_HASH_EMPTY, explicitly call
mtev_hash_init() to initialize hash tables.
=> Explicitly Use mtev_hash_init To Init Hashes

src/noit_check_tools.c, src/noitd.c
We need to call this to initialize the hash table before we start
loading checks.
=> Call noit_check_tools_shared_init() Much Earlier

src/modules/Makefile.in, src/modules/lua_check.c
I'm not sure if it's a good idea to let lua.so AND noit_lua/noit_binding.so depend on $(LUA_MODULE_OBJS) but this at least fixed my issues with undefined symbols in either lua.so or noit_binding.so
=> Fixed undefined symbol issue and cleared compiler warning

src/noitd.c, src/stratcond.c
noit_mtev_bridge_init uses hash tables initialized in libmtev's init
function.... we need to make sure we call this AFTER we initialize
those, not before.
=> Call noit_mtev_bridge_init After libmtev Init

src/noitd.c
to be able to use e.g. `noit.checks_do` in lua `noit_metric_director_init()` must have been called first
=> moved noit_metric_director_init() in front of the module initialization

src/modules/snmp.c
Missed initializing the target_sessions hash table when calloced... add
the initialization.
=> Add Initialization Of target_sessions In SNMP Check

src/modules/lua_check.c
without that I godd flooded with `warning: null hashtable in mtev_hash_store... initializing`
=> initializing lmc->pending

src/noit_check.c
There are a bunch of hashes in noit_check.c that could theoretically get
hit from multiple threads.... initialize them as locking.
=> Lock Hashes In noit_check.c

src/noit_check.c, src/noit_check_rest.c, src/noit_conf_checks.c
Replace metrics into the previous stats_t structure
instead of swapping it and freeing the table.  Update
the reporting to more concisely show metrics by default.
=> Make the "previous" stats_t cumulative.

src/modules/httptrap.c, src/noit_check.c, src/noit_check.h, src/noit_metric.c, src/noit_metric.h
If httptrap submissions contain an extended value with _fl, it
will attempt to accumulate (+) continuously or average (~) over
the period.  If the logging is immediate, averaging over the
period is avoided for replacement as individually reported
values will be averaged upstream.
=> Support { "_fl": "+|~" } operations to accumulate and average.

src/noit_metric_rollup.c
The derivative is calculated based on the last value seen, even if it's not in the current window. Hence, even if the current window is empty (accu->accumulated.type == METRIC_NULL) the derivative can be calculated.
=> Bugfix: rollup has to access last value even if it's in the last window

src/modules/histogram.c, src/modules/histogram.h, src/modules/lua_check.c, src/noit_check.c, src/noit_check.h, src/noit_check_log.c
This allows us to publish histograms from lua via `check.immediate_histogram(metric, encoded_histo, whence_s)`
The lua part is already tested by the caql broker, the refactored version of `histogram.c` is not however.
=> Immediate histo

src/noit_check_tools.c
We were crashing on a null JSON array object.... check for the
condition, log, and move on when we hit it.
=> Fix Crash When NULL Item Found In Array

src/modules/histogram.c, src/modules/histogram.h, src/modules/lua_check.c, src/noit_check.c, src/noit_check.h, src/noit_check_log.c
This allows the following lua code:
check.immediate_metric_double('name', 1.0, 123, 456)
This value should then be distributed at the timestamp 123.456
NOTE: currently for some reason the usecs are ignored. So the actual M message stores the time 123.000
=> Timed immediate metric

src/modules/ping_icmp.c
It only uses two FD sockets for ICMP responses, so it is mostly
single-threaded already. There is no benefit to having the
noit check infrastructure itself in another thread, and some risk
to doing so. So, make the ping_icmp's noit_module single-threaded.
=> mark ping_icmp noit-module as thread-unsafe.

src/modules-lua/noit/module/cloudwatch.lua
Currently, cloudwatch pushes missing metrics into the response with
a null value.  This is unlike other checks that omit them entirely
and causes confusion further down the line.
We should just treat them line any other check would, and not put
them in the response
=> Have cloudwatch treat missing data like all other checks

src/modules/lua_check.c, src/noit_check.c
This reverts some parts of https://github.com/JonasKunze/reconnoiter/commit/97c5c2142634286fde3578e79cc2af284c45ee38
I've left some parts of this commit (essentially noit_check_path) as I'm using it in another feature branch
=> removed non thread safe check.path from lua

src/noit_filters_rest.c
It seems like while splitting #321 to #324 and #325 I've made a copy paste error. in #325 it says if(old_seq >= seq && seq != 0) which is correct: If the seq was zero it may stay zero.
=> Bugfix: wrong logic checking seq of filtersets

src/stratcon_iep.c
`float` does not have enough precision to represent current unix
time_t values on our supported architectures, so we should be
casting `struct timeval#tv_sec` and `#tv_usec` to double, instead.
=> improve accuracy of stratcon_iep_age_from_line routine.

src/java/src/com/omniti/reconnoiter/StratconMessage.java
Its possible we can get a timestamp in that has more preceision than
ms, so in that event, make sure we are only pulling out 3 digits
to convert and not the entire value
=> Protect TS conversion from very precise timestamps

src/noit_metric.h, src/noit_metric_director.c, src/noit_metric_director.h
The timeout is 10s. Windows are cleared every 5s -> a duplicate is found if two messages are arriving within 10s up to 15s depending on the timing of the prune event
=> metric_director dedupes incoming messages

src/modules/external.c, src/modules/external_proc.c, src/modules/external_proc.h
Also provide a config variable "max_output_len" which will let this be increased to an arbitrary size
Also add a new metric to the check output which indicates if the output was truncated ala http checks.
=> CIRC-1134: Default to 256K for external check output reading

src/modules-lua/noit/module/resmon.lua, src/modules-lua/noit/module/resmon/consul.lua
User supplies the Consul health check url (e.g.: http://host:8500/v1/health/state/critical) and optionally the ServiceName and CheckName she cares about.  We generate mostly text metrics from the consul output, flattening into metric names as we go.
The blacklist params only apply to 'state' based health checks
The user can also supply a datacenter name to have that passed to the consul REST call.
=> Consul check

src/modules-lua/noit/AWSClient.lua
Cloudwatch is super annoying in that if they don't have a value for
something, they simply don't return it.
I haven't looked at every single metric, but I think in most every
case this would mean the value is 0 (like requests, etc) because if
there was a value, it would be returned.
So, when we get back a datapoints section that is empty, loop over
the stats we requested, and return a 0 value instead of nothing for
that metric
=> Set "null" cloudwatch values to 0

src/modules/external.c, src/modules/external_proc.c, src/modules/external_proc.h
The external check should report "truncated" as a stand-alone metric
rather than making it part of the output string; putting it in the
output string can break parsing regexes.
This will cause issues if there is a configured metric called
"truncated", but that's better than the previous solution.
=> Make Truncated A Standalone Metric For External

src/noit_check.c, src/noit_message_decoder.c
The M format is \n terminated and the \n is not supposed to be part
of the value itself.  The vlen of th string included the \n and it
was being copied during the M record decoding process.
=> Do not include \n in the string value of M records.

configure.in, src/Makefile.in, src/modules/ping_icmp.c, src/noit_check.c, src/noit_check.h, src/noit_check_rest.c, src/noit_check_tools.h, src/noit_clustering.c, src/noit_clustering.h, src/noit_conf_checks.c, src/noit_filters.c, src/noit_filters.h, src/noit_filters_rest.c, src/noitd.c
This supports automatic synchronization of all checks and filtersets.  It also does automatic assignment of check-node assignment for the purposes of "running checks."  This is complete for pull-based checks, but push-based checks will need more facilities.
=> Clustering

src/modules/httptrap.c, src/noit_check.c, src/noit_check.h
Allow setting timestamps in asynch data send up for the httptrap check.
=> Httptrap timestamp processing

src/noit_check_log_helpers.c
We had an instance of inverted logic; we need to free this buffer if
compression is disabled, not the other way around.
=> Fix Memory Leak When Compression Disabled

src/modules/external.c
When cleaning up the check, we need to free the output and error fields
of the check.
=> Fix Memory Leak In External Check

src/java/src/com/omniti/jezebel/check/jmx.java, src/modules/jmx.xml
allow users to set mbean_properties_(.+) that will act like an OR filter for mbean objects, if they match the props, let them through.
This means we don't have to pull every object and pass it back to noit, potentially killing it while it tries to parse the large XML docs that can be created.
=> Jmx object filters

src/modules-lua/noit/module/cloudwatch.lua
Watching a cloudwatch check would cause all (sometimes excepting the first 1-2) metrics in the check to stop being collected for the lifetime of the watch.
Given that both the original and transient check share a lua state, the transient check would fire frequently enough to beat the original check to updating their shared cache. However, the transient check's timeout was much too low and so would be timed out before it processed more than one or two metrics. The original check would then find the recent but incomplete set of metrics in the cache and use that rather than pulling the full set.
=> prevent transient cloudwatch checks from pulling data

src/noit_module.c
We were failing to release all of the conf locks we were acquiring in
noit_module_init.... fix to release them properly.
=> Fix Lock Leak In noit_module_init

src/modules/httptrap.c
1) Don't allocate the call closure until we're past all of the validity
checks
2) If we get into the error condition, we need to clean up properly.
=> Fix Memory Leak In Httptrap Module

src/modules/dns.c
We were leaking memory on bad DNS checks; need to free the eventer stuff
manually if we're not coming from an eventer callback.
=> Fix DNS Memory Leak

src/noit_check_log_helpers.c, src/noit_websocket_handler.c
There were a couple of significant memory leaks - one related to not
freeing metric data on streaming and one related to not cleaning up
compression data. Fixed both of these.
=> Fix Memory Leaks Related To Websockets And Decompression

src/stratcon_jlog_streamer.c
If the XML and hash didn't agree, we could never set n = 0 and then
start filling in the array at -1.  This is simplified and we now
treat surgery on the XML separate from in-memory pruning.
=> Never iterate starting at -1.

src/modules/postgres_ingestor.c, src/stratcon_datastore.c, src/stratcon_ingest.c, src/stratcon_ingest.h
When sweeping through stratcon files, there are occasionally trash files
in the directory that we ignore, but we really need to clean up.
Added a new paramter to the sweep function, "unlink_test", which is a
function that determines if we should unlink an invalid file. If this
returns true, we will attempt to unlink the file.
This is currently hooked up to unlink a valid raw_ingestion file with a
".tmp" extension at the end.
=> Add Ability To Test For And Unlink Trash Files In Stratcon Sweep

src/modules/reverse_check.c
* move mtev_reverse_socket_acl to `post_init`.
* move `check_config_fixup_hook_register` back to `dso` init.
=> fix reverse-socket ACL false-negatives.

src/noit_filters.c
We were incrementing the reference count every time we looked through
the filters, but only decrementing it in one specific case; we need to
decrement the reference count every time we finish checking. Otherwise,
we could leak memory.
=> Fix Ref Count Issue In Noit Filters

src/noit_metric_tag_search.h
C++ cannot address the inline structs
=> unnest noit_metric_tag_search_ast structs for easier use from C++

src/noit_check.c
Fixing XML parsing errors when the metric name contains brackets e.g. `output[1]`
=> Put metric name into name attribute, not in the tag

test/t/testconfig.js
Somehow it get's created sometimes, and sometimes not. Likely a race.
We just add a check here to avoid that failure condition.
=> test: Create log-root if it is not there

src/noit_check.c, src/noit_check_rest.c
Not really sure why, but this seems to avoid parsing problems of XML returned by the
/cluster/updates endpoint.
Payloads like
```
<histogram:value name="output[1]">add</histogram:value>
```
were persisted as
```
<output[1]>add</output[1]>
```
Now this is fixed.
=> Fix namespacing issue in noit clustering payloads

src/stratcon_jlog_streamer.c
Take output in stratcon_jlog_streamer and send it to specific outlets
rather than standard noit_error and noit_debug. Will allow logging these
specific errors without turning on the firehose.
=> Add Dedicated Outlet For stratcon_jlog_streamer Errors

.gitignore, src/Makefile.in, src/noit.conf.in, src/noit_check.c, src/noit_message_decoder.c, src/noit_message_decoder.h, src/noit_metric.c, src/noit_metric.h, src/noit_metric_private.h, test/Makefile.in, test/test_tags.c
* Expand tag characters to a large alowable set
* Define form as name|ST[..]|MT{...}
* |ST and |MT are omitted if no such tags are there
* Base64 tags are decoded before sorting.
* Tags within groups are unique and sorted.
* Only tags parts (key or value) are base64 encoded if they cannot be expressed otherwise.
* Canonicalize on the way into the set metrics path for checks.
* Canonicalize on the message decoding path (extra alloc if non-canonical)
=> Make metric names canonical with respect to tags.

src/noit_message_decoder.c, src/noit_metric.c, test/test_tags.c
If the records contained clean and canonical messages we would
pasrse the stream tags but have our tag points into a freed
buffer.  This will detect that case and adjust the pointers back
into the originally canonical metric name.
=> Fix stream tag pointers for pre-canonicalized messages.

src/modules/noit_lua_libnoit_binding.c
This restores the behavior of returning the full metric name, instead
of truncating stram tag. In this way we keep the policy that a metric
is uniquely identified by UUID+name.
=> Return "metric_name_with_tags" to lua

src/modules/ping_icmp.c, src/noit.conf.in, src/noit_check.c, src/noit_check.h, src/noit_check_rest.c, src/noit_check_tools.c, src/noit_clustering.c, src/noit_clustering.h, src/noit_conf_checks.c, src/noit_conf_checks.h, test/t/cluster/120_cluster_noit.tjs, test/t/testconfig.js
Deleting checks on clusters requires delete replication and seq manipulation.
The seq must be increased and the check considered a tombstone until it has
been replicated everywhere and then it can be formally deleted. If this isn't
done, then old nodes can come back online and reinstantiate the check.
=> Support deleteing checks on clusters.

src/noit-web/css/theme.css
Empty fields would destroy the table structure without this change.
=> Fix alignment of "Check Details" table

src/noit_filters.c, src/noit_metric.c, src/noit_metric.h
* implement filter attributes `stream_tags` `measurement_tags`.
* use them in addition to a metric regex if provided.
=> Implement tag search filtering for metrics.

src/noit_clustering.c
```(gdb) bt
#0  0x00007f327a8c451d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f327a8bfe1b in _L_lock_812 () from /lib64/libpthread.so.0
#2  0x00007f327a8bfce8 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000058c774 in noit_cluster_mark_filter_changed (name=0x6020000addf0 "allowall",
vpeer=0x60f00000c610) at noit_clustering.c:220
#4  0x00000000005ae439 in noit_filtersets_build_cluster_changelog (vpeer=0x60f00000c610) at noit_filters.c:804
#5  0x000000000059229e in noit_peer_rebuild_changelog (peer=0x60f00000c610) at noit_clustering.c:190
#6  0x00000000005913cc in update_peer (node=0x614000020860) at noit_clustering.c:644
#7  0x0000000000590366 in attach_to_cluster (nc=0x6110000dc920) at noit_clustering.c:685
#8  0x000000000058ff05 in cluster_topo_cb …
```
=> unlock mutex before update_peer to prevent deadlock

src/Makefile.in
Preserves these artifacts for standard installs, but don't deliver
them in the "nolibs" case.
=> Move IEP bits to regular stratcond install target

src/noit_check_resolver.c
The fetch function should init-on-demand to prevent crashes when
uses occur prior to initialization.
=> noit_check_resolver should protectively init.

src/noit_module.c
This variable contains a PCRE (default `.`) that will be
applied to each noit check module.  Module (names) that do
not match this regular expression will be skipped.
For example `NOIT_MODULES="^(selfcheck|prometheus)"` will only
load modules starting with `selfcheck` or `prometheus`.
=> Support NOIT_MODULES environment variable.

src/modules-lua/noit/AWSClient.lua
With a space in the metric name (or anything passed to escape) lua
would generate an error: "invalid capture index"
The fix is to just pull the %s into the first gsub and then remove
the second that looks for just spaces since they will ne taken care
of
=> Fix escape function to work with spaces

src/noit_clustering.c, test/busted/lua-support/reconnoiter.lua
There was a race condition that could cause us to not think
we needed to send the finalization of a replication batch
(the zero length batch) and it would cause indefinite replication
lag when no new replication events percolated.
=> Always finalize pending cluster replication batches.

src/noit_check.c, src/noit_check.h, src/noit_check_rest.c, src/noit_conf_checks.c, test/busted/run-tests.sh, test/busted/simple/delete/delete_spec.lua
* target_ip was modified while node was in list.
* target was modified while node was in list.
* removals were skipped for sequenced checks
(which should be done if the check will be readded)
=> Fix sloppy polls_by_name maintenance.

src/noit_check.h, src/noit_check_log.c, src/noit_filters.c
The XML config change rate is too high and cannot be maintained
reasonable using libxml2.  Since we're trying to manage concurrency
more than total historic unique metrics, it makes sense to only
manage these hashes transiently.  Additionally, as metrics come and
go, it makes sense to refresh the automatic set periodically. We
default this refresh to 300000ms (5 minutes) and allow it to be
set via filter_flush_period (0 to disable).
=> XML backed *_auto_add rules are untenable.

src/noit_metric.c, src/noit_websocket_handler.c
We were just using the base metric name, ignoring stream tags. These
need to be included when sending to websockets, since they are
considered part of the metric name.
=> Send Full Metric Name With Tags To Websockets

buildtools/mkversion.sh
The value returned by `git name-rev` when in detached-HEAD is
unpredictable and of low value, since it will pick the nearest symbolic
name in lexicographic order, which really does nothing for
communicating "what branch we're on".
Instead, use `git symbolic-ref` to resolve HEAD, and if it's empty,
we must be detached and should just say so.
This solution also works around the lack of a `--short` option to
symbolic-ref in older git versions, so we will still get "master"
instead of "refs/heads/master", for example.
=> mkversion.sh should detect detached HEAD state

src/Makefile.in, src/noit_mtev_bridge.c, src/noit_mtev_bridge.h
My debug logs are full of:
```
[2018-11-02 13:39:37.376822] [debug] [t@6853/e:default/7,noit_check.c:2547] q._caql`c_2438_215752::caql <- [OK]
[2018-11-02 13:39:37.376845] [debug] [t@6853/e:default/7,noit_check.c:2552] q._caql`c_2438_215752::caql -> [available:good]
[2018-11-02 13:39:37.392899] [debug] [t@6851/e:default/5,noit_check.c:2547] q._caql`c_2_198461::caql <- [OK]
[2018-11-02 13:39:37.392921] [debug] [t@6851/e:default/5,noit_check.c:2552] q._caql`c_2_198461::caql -> [available:good]
```
This change should give me a way to avoid those.
=> Log to */noit log_streams per default

src/modules/graphite.c, src/noit.conf.in, src/noit_message_decoder.c, src/noit_metric.c, src/noit_metric.h, src/noit_metric_private.h, test/Makefile.in, test/busted/libnoit/tags_spec.lua, test/test_tags.c
This determines if the cat:val is too long and
uses a hueristic to size them appropriately and
replace with the largest possible prefix and a
suffix of _tldr_<sha1_hex> of the original cat
or val.
=> If tag cat:val is too long truncate uniquely.

src/modules/noit_lua_libnoit_binding.c, src/modules/noit_lua_noit_binding.c
caql-broker tag-search PR: https://github.com/circonus/caql-broker/pull/81
Tests are in the caql-broker repository, since there is no test "harness" for lua in here. (TODO: Move tests here)
=> metric_director extensions for lua tag-search

src/modules/httptrap.c
httptrap is rejecting PUTs when one or more metrics have names > 255 characters. This happens frequently when stream tags are added to metric names. Using MAX_METRIC_TAGGED_NAME from noit_metric.h. Unclear if the 255 limit set in httptrap is intentional due to a constraint somewhere else in the metric handling path.
=> upd: max metric name length limit to MAX_METRIC_TAGGED_NAME

src/modules/httptrap.c, src/noit_check.c, src/noit_check.h
Normalize on single define `NOIT_DEFAULT_TEXT_METRIC_SIZE_LIMIT` in:
`noit_check.c`
`noit_check.h`
`modules/httptrap.c`
=> fix: normalize max text metric value size

src/modules-lua/noit/test/tags.lua, src/noit_check_rest.c, src/noit_filters.c, src/noit_filters_rest.c, src/noit_metric.h, test/busted/simple/filters/filter_spec.lua
* metric matching only matches against the metric base name (not tags).
* __name is inserted and made available to the stream_tags expression.
=> Fix and test filter stream_tags.

src/modules/httptrap.c
This will help debug issues with timeouts at MLB, could also help with cause of 500's.
=> CIRC-3596 Add some mtev logging for httptrap on errors or httptrap debug header

src/modules/httptrap.c
This PR adds some code cleanup, and adds the check uuid to each log message with a unique tracking number assigned on each REST API invocation, so that it will help us follow a particular request that fails in a stream of simultaneous incoming traffic. If the debug/httptrap stream is enabled, the additional logging will be visible for diagnosis of a particular problem.
=> Better httptrap logging

src/modules/httptrap.c, src/modules/prometheus.c, src/noit_check.c, src/noit_check.h, src/noit_check_log.c, src/noit_check_log_helpers.c, src/noit_fb.c, src/noit_metric.h, src/proto/bundle.proto
* Enhance the metric_t to have an optional struct timeval.  If it is
set to something other than {0,0}, then it should override the
encapsulating "thing."
* Extend protobuf definition to have a timestamp in the metric.
* Alter logging and reading to support reading/populating the
per-sample timestamp data.
* Fix some bugs in the httptrap batching.
* Port the batching from httptrap into the prometheus module.
=> Bigger, better batches.

src/java/src/com/omniti/jezebel/check/jmx.java
- Adds java.lang.Object to the list of MBeanAttributeInfo.getType() values allowed for MBean attributes for which this check will attempt to create metrics.
- The functionality of the getMetric method still ensures that the attribute value is an instance of a valid type for a metric to be created.
=> CIRC-3670: Add Object to allowed JMX types

src/modules/opentsdb.xml
Mark content of <code> as CDATA for XML validity purposes.
=> Fix invalid XML by protecting text block as CDATA

src/Makefile.dep, src/modules/noit_lua_libnoit_binding.c, src/noit_metric.c, src/noit_metric.h, src/noit_metric_tag_search.c, src/noit_metric_tag_search.h
* add a hook `noit_metric_tagset_fixup`
* add `noit_metric_tag_search_evaluate_against_metric_id`
* add `noit_metric_tag_search_evaluate_against_tags_multi`
The `noit_metric_tag_search_evaluate_against_metric_id` function is
preferred as it does all the hard work of introducing the __name and
__check_uuid tags into the stream and check tagsets, respectively.
It also calls the hooks so that third-parties can manipulate the
three tagsets: `check`, `stream`, and `measurement`.
=> Support multiple tagset evaluation for search.

src/modules/check_test.c, src/modules/check_test.h, src/modules/ping_icmp.c
PIng_icmp currently fails to match up ping responses with a test check, so running a test check always fails.  This was due to a tightening up of code done 8 months ago where code was added to make sure that the ping is coming from a valid check being polled (but test checks are not in the polling list because they are temporary).
To fix this we add a new hash and access function in the testcheck module which allows another check module to see if the check is a test check.  This function is dynamically linked and will do nothing if the testcheck module is not loaded.  If ping_icmp cannot find the check by doing noit_poller_lookup(), then it will fallback to looking for a test check (if that module is loaded).
=> CIRC-3566 Ping_icmp module test check fixes

src/noit_filters.c
The auto add filters need a cycled clear to allow new
metrics to be learned.  We were clearing all hash-based rules
instead of just the auto_add ones.
=> Prevent wiping out explicit hash-based filtersets.

src/noit_filters.c, src/noit_filters_rest.c, test/busted/simple/filters/filter_spec.lua
Previously <metric>foo</metric> filtersets would match only
against the untagged portion of the name.  This change will allo
<metric>foo|ST[a:b]</metric> match exactly that canonical name.
Improve filter test to test new metric name matching, more
thorough evaluation of existing test, and auto_add hash filters
including reset.
=> Support filering of metrics with tags using canonical names.

src/noit_metric.c
We were trying to do a memcmp of 2 bytes without verifying that we had
two bytes of data available to look at. Fix to confirm that we have that
before doing the memcmp.
=> Fix Overflow In Tag Parsing

src/noit_clustering.c
Example:
```
[2019-07-19 19:22:58.101762] [error/cluster] Error fetching https://caql-broker-caqlbroker1-mnc4:43191/filters/updates?peer=19a27dc1-6e4f-4b48-a00f-9ba095955d94&prev=0&end=18: 0/403
[2019-07-19 19:22:58.602756] [error/cluster] Error fetching https://caql-broker-caqlbroker1-mnc4:43191/checks/updates?peer=19a27dc1-6e4f-4b48-a00f-9ba095955d94&prev=0&end=8902: 0/403
[2019-07-19 19:22:59.104110] [error/cluster] Error fetching https://caql-broker-caqlbroker1-mnc4:43191/filters/updates?peer=19a27dc1-6e4f-4b48-a00f-9ba095955d94&prev=0&end=18: 0/403
```
=> Log check replication errors to the error log

src/modules/collectd.c, src/modules/httptrap.c, src/modules/prometheus.c
It's not how much you've received, it is how much we've read
from the wire.  If we can't decompress something we could get
stuck thinking there should be more data when the http client
has already ready everything.
=> Fix how modules are determining complete payloads.

src/noit_metric_tag_search.c, src/noit_metric_tag_search.h
Add a pcre_extra and free it (allowing clients to
optionally leverage it).
=> Add an optional pcre_extra field to tag search nodes.

src/modules/lua_check.c
This will expose the runtime, but not register it as
a loader. Useful for 3rd-parties that want to piggy-back
off this runtime.
=> Allow loading of the lua runtime as a generic module.

src/modules/histogram.c, src/modules/histogram.h, src/modules/httptrap.c, src/noit_check.c, test/busted/cluster/histogram/histogram_spec.lua
Histogram submission is intentionally jittered when running in
a clustered configuration. However, when _ts is specified, that
jitter should not be applied. This change makes it such that
jitter is not applied when logging a histogram with an explicit
_ts setting.
=> Fix clustered histogram submission with explicit _ts

src/modules-lua/noit/module/resmon.lua
This reduces reading from a hostile endpoint sending small chunks
(10-20bytes) for a 1Mb payload from 25s down to 0.5s.
=> Optimize for reading small chunks in a stream.

src/modules/histogram.c, src/modules/httptrap.c, src/modules/lua_check.c, src/modules/statsd.c, src/noit_check.c, src/noit_check.h, src/noit_check_tools.c, src/noit_socket_listener.c, test/busted/lua-support/reconnoiter.lua
This is a breaking change as metric names will change.  However,
the prior implementation was severely broken and not cluster-capable.
This should use histograms where it makes sense.  For counters,
we count in the zero bucket so that no one attempts to sum them
(they should count them).
=> Redo statsd to use histogram intelligently.

test/busted/checks_data/httptrap/httptrap_spec.lua
libmtev 1.9.3 has made mtev_stderr messages asynch. This test depends on
these log messages to gauge correctness. We need to increase the number
of times we check to make sure we see everything that's available here.
=> Fix HTTPTrap Test

src/modules/httptrap.c
Reading only up to the content length makes no sense as the
content-length is the compressed version and the read length
is the decompressed version.  We should just read as much as
we can always.
Fixes CIRC-4425
=> Fix short reads of compressed httptrap submissions.

src/noit_metric_tag_search.c, test/test_tags.c
Now `and(foo)` and `and(foo:)` and `and(foo:/^$/)` all work against
tags that arrive as `foo:`
=> Fix tag search evaluation with empty tag values.

src/modules/external.c, src/modules/histogram.c, src/modules/mysql.c, src/modules/postgres.c, src/modules/prometheus.c, src/modules/snmp.c, src/noit_check_log.c, src/noit_filters.c
Some of the buffers were way too short to hold certain metric/filterset
names. Extend them to allow the maximum length.
=> Extend Metric/Filterset Length Buffers

src/modules/ping_icmp.c, src/modules/prometheus.c, src/noit_check_tools.c, src/noit_check_tools.h, src/noit_socket_listener.c
We already had check-based thread selection in noit_check_tools.
This expands that to allow for check-based, module-based, and
module-name based logic (all shared).  This updates ping_icmp, graphite,
and prometheus checks to all use this shared logic.
The new logic will back off the names heirachically based on underscore:
noit_check_<uuid> (if check based)
noit_module_graphite_pickle
noit_module_graphite
noit_module
noit
-> default (NULL)
=> Make pool selection heirarchical and unify logic.

src/noit_check.c
This should solve issues where removing large numbers of checks
performs to much work with the master poller lock held.
=> Decouple the XML culling from the check deactivation

src/modules/noit_lua_libnoit_binding.c, src/noit_metric_director.c
This PR adds a method .ctags to the noit_metric_id lua object, which returns the fixed-up check tags associated to the noit message.
This will be used in CAQL-broker, to forward metric metadata from find() queries.
=> CIRC-4816 Expose check-tags to lua

configure.in, src/modules/check_test.c, src/noit_check.c, src/noit_check.h, src/noit_check_lmdb.c, src/noit_check_lmdb.h, src/noit_check_rest.c, src/noit_conf_checks.c, src/noit_conf_checks_lmdb.c, src/noit_conf_checks_lmdb.h, src/noit_lmdb_tools.c, src/noit_lmdb_tools.h, test/busted/lua-support/reconnoiter.lua, test/busted/simple/delete/delete_spec.lua
Added a flag to the "checks" configuration - "use_lmdb" - that, if set to true,
will enable an LMDB db for storing checks instead of XML. This will require setting
an "lmdb_path" field as well to tell it where the LMDB database will be stored. In
addition, there is a true/false flag, "convert_xml_to_lmdb", that will convert the existing
XML backingstore to use LMDB.
LMDB reads/writes are considerably faster than XML configuration - this path will enable
a significant speed-up when reading/writing checks - particularly noticeable if there are
a considerable number of checks.
=> CIRC-4638 - Add LMDB Backing Option For Checks

src/modules/noit_lua_libnoit_binding.c, src/noit_metric_director.c, src/noit_metric_director.h
With this PR, the lua functions:
```
noit.metric_director_subscribe()
noit.metric_director_subscribe_checks()
```
Return the current interest counters, after the adjustment.
This is, so that we don't have to do our own accounting, when using those functions elsewhere.
=> [CIRC-4944] metric_director: Return current count after adjustment

src/noit_clustering.c
This avoids timeout events when replicating brokers with a large number (10K+) of active checks.
Manually tested in dev.
=> Noit clustering: Fetch clusters and filtersets in batches (of 500)

test/busted/cluster/delete/delete_spec.lua, test/busted/cluster/histogram/histogram_spec.lua, test/busted/lua-support/reconnoiter.lua
There's a pending change in libmtev that uses a header to force cluster
puts to write out the configuration file immediately. Add a header to
the tests that use this so that when that change goes live, we'll use
it. It will have no effect until the libmtev change lands.
=> CIRC-5074 - Use Conf Sync Flag In Cluster Busted Tests

src/modules/statsd.c
Some apps will send stats with no trailing \n and we
were skipping that character.
=> Don't assume we can ignore that last character.

aclocal.m4, configure.in, src/modules/external.c, src/modules/statsd.c, src/noit_clustering.c, src/noit_filters.c, src/stratcon_jlog_streamer.c
* Fix a set of format truncation warnings.
* Suppress stringop-trunctation for flatbuffers.
=> Allow -Werror on GCC 9.

src/noit_check_lmdb.c
We were accidentlaly calling "response_ok" no matter what - even if we'd
already set it, or were setting something else. Change to remove the
extra call.
=> Fix Double Status Set When Showing LMDB Checks

test/Makefile.in
Changed "make check" to run the test suite with both XML and LMDB
backingstores for checks and filtersets. Added "check-xml" and
"check-lmdb" to run one or the other.
=> CIRC-4638 - Test Both XML and LMDB Checks/Filtersets

src/noit_filters_lmdb.c, test/busted/lua-support/reconnoiter.lua
If we fail to convert an XML filterset to LMDB, we should log exactly
what happened and not remove the filter from the XML. That way, we don't
lose the filterset and can debug later.
=> CIRC-4638 - Better Error Logging When Conversion Fails

test/busted/simple/delete/delete_spec.lua
This test is occasionally failing due to a race; a fix is in the works,
but in the meantime, we should flag the test as pending.
=> Flag Delete Torture Test Pending

src/noit_check.c, src/noit_check_lmdb.c, src/noit_check_lmdb.h, test/busted/lua-support/reconnoiter.lua, test/busted/simple/delete/delete_spec.lua
The check recycle bin - where we clean up checks that have already been
deleted, but not removed from the disk - was encountering a race where
we could potentially accidentally delete a check we're attempting to
restore.
When cleaning the recycle bin, check the config to make sure we're still
set for deletion. If we're not - don't delete it.
=> CIRC-5150 - Fix Race In Check Recycle Bin

src/noit_check.c, src/noit_check.h, src/noit_check_lmdb.c, src/noit_check_rest.c, src/noit_filters.c, src/noit_filters.h, src/noit_filters_lmdb.c, src/noit_filters_rest.c
When interacting with the check or filterset DB - add a header to each
that will inform the caller the source of the data.
=> CIRC-5181 - Add DB Type Response Headers

src/noit_check.c, src/noit_check_lmdb.c, test/busted/simple/check_config/check_config_spec.lua
We were skipping empty XML elements when converting from XML to LMDB.
Make sure we store these as keys will null values in the DB rather than
skipping them. Add tests to confirm that this works.
=>  CIRC-4638 - Fix Empty XML LMDB Conversion

src/modules/noit_lua_libnoit_binding.c, src/noit_metric_director.c, src/noit_metric_director.h, src/noit_metric_tag_search.c, src/noit_metric_tag_search.h
* Make the direct interests thread safe (cross-thread registration)
* Support registering searches with a lane
* Simplify the distribution path
* Make noit_metric_search_tag_ast_t ref counted.
=> Facilities to register searches to director lanes

src/modules/noit_lua_libnoit_binding.c, src/noit_metric_director.c, src/noit_metric_director.h
* This avoids work for search patterns that have exact metric name
matching.
* This also simplifies the logic a bit by not having thread_asts at
multiple levels of the heirarchy by explicitly storing the "any check"
as the null uuid and "any metric name" as the "" blank name thus
leveraging the normal check_search_t and name_search_t retrieval
mechanism.
=> Allow search interests so specify exact metric_name

src/modules/noit_lua_libnoit_binding.c, src/modules/noit_lua_noit_binding.c
* Add an explicit constructor from parts.
* Add `canonical_name` and `tagless_name`
* Add `{stream,check,measurement}_tags` accessors that work like IRONdb
search items.  This allows simple exctraction of stream tags from
canonical metric names uses the one-true-code.
=> metric_id should act like an IRONdb search result.

src/noit_check_log.c, src/noit_check_log_helpers.c, src/stratcon_iep.c
* Make IEP filtering apply to B* and H* records.
* Change the default filter to 5 minutes and make configurable.
* When encoding a set of metrics, if the timestamps are all set then
rewind the encapulating line's timestamp to the latest of those.
* Alter the BF format before it is put into use to include a timestamp.
=> Improve time encoding on B* records and IEP filtering

buildtools/mkversion.sh, src/Makefile.in, src/noit_version.c
* Expose three global symbols to aide debuggers.
=> Make the version cleaner and avoid snprintf.

src/modules/external.c, src/modules/graphite.cpp, src/modules/mysql.c, src/modules/ping_icmp.c, src/modules/postgres.c, src/modules/selfcheck.c, src/modules/test_abort.c, src/noit_check.c, src/noit_socket_listener.c
This requires module cleanup functions to be safe when run multiple
times.  This fixes lingering sockets on checks that have listeners
which is important when the check is modified but the port is unchanged
because the stale check will still have an active listener, but will
not handle arriving data which can cause loss.
=> Call module cleanup immediately on removal.

src/modules/lua_check.c, src/noit_check_log.c, test/busted/simple/websocket/websocket_spec.lua
Lua cleanup and timeout both free the resume info. The timeout can
cause logging which can fail which can induce a cleanup causing a
free before out intended free.
=> Fix cross call double free in lua cleanup.

src/Makefile.in
Circonus packages noitd and jezebel separately now, and this is
necessary to avoid conflicting files.
=> Remove Java prereqs from noitd-only install target

src/modules/statsd.c, src/noit_message_decoder.c, src/noit_metric.c, test/busted/checks_data/statsd/statsd_spec.lua, test/test_tags.c
* Allow decoding of bare tag names `foo` as `foo:`
* Fix decoding of DD-style statsd tags in multi-line mode.
=> Fix bare tags and statsd DD tag decoding

src/noitd.c
In noitd child_main before dropping privileges we call log reopen which,
conceptually, would not alter/create anything.  However, if there is a
jlog precommit buffer and the last segment is full, it will cause a
flush which can cause a newly created segment owned by the wrong user.
Call instead mtev_conf_log_init which will reinitializing the logging
system under dropped effective privileges.
=> reopen log files with dropped privileges.

src/noit_check_log_helpers.c, src/stratcon_datastore.c
BF records do not have UUIDs plain.
=> Datastore should fallback to base interim jounral.

src/noit_metric.c
Fix an off-by-one-error that refused empty tag sets in canonicalization.
=> Allow foo|ST[] as a valid metric name.

src/modules-lua/noit/module/tcp.lua
Recent PR had a typo in an if statement, breaking the tcp check.
Fix herein.  Apologies.
=> fix broken tcp check

src/modules/statsd.c
Use recvmmsg to accept statsd UDP traffic
- https://circonus.atlassian.net/browse/CIRC-6124
- All tests pass
=> CIRC-6124 - Use recvmmsg for Statsd UDP Reception

src/noit_check_lmdb.c, src/noit_check_lmdb.h, src/noit_check_rest.c, src/noit_lmdb_tools.c, src/noitd.c
When configuring a check via LMDB, offload the work into a jobq rather than doing it in the
main eventer pool.
=> CIRC-6377 - Set LMDB Checks In Jobq

src/stratcon_jlog_streamer.c
Quiet warning because eclipse paints the entire switch statement
yellow
=> CIRC-6516 - Quiet Warning

src/noit_message_decoder.c
The code assumed that the message was null terminated which could
cause a read overrun.  Respect the stated length.
=> Respect the fixed message len for decoding.

src/modules/httptrap.c, src/modules/httptrap.xml
The old behavior can be restored by setting the `fanout` config option
in the module config or the check config.
=> Make httptrap fanout ingestion work by default.

configure.in
Needs to use the options from the libmtev-asan build, not the standard
one.
Source needs C++17 these days.
Fix bare single quote that was messing with syntax highlighting.
=> Use a different mtev-config when building ASAN

src/modules/httptrap.c
Logic for disabling fanout on httptrap checks was reversed - would always be set to true.
=> Fix Reverse Logic On HTTPTRAP Fanout

test/busted/run-tests.sh
#714 added a library preload to the Lua test harness if any `ASAN_*` environment variables were set. This was the case even for non-ASAN builds due to some pre-existing ASAN work in `run-tests.sh`. Non-ASAN builds are now clean of ASAN-related environment variables.
=> Fix run-tests for non-ASAN builds

src/modules/ping_icmp.c, src/noit_check.c
- Properly decrement the reference count from all the eventer
callbacks for ping handlers
- Fix double free
=> CIRC-6923 - Bad Ref Count

src/noit_check.c, src/noit_check.h
- Use a lock to avoid races between the ref count
and lookup in the skip list
- In noit_check_add_to_list:
- Avoid race on mtev_skiplist_remove
- Pointer removed is not always identical to its
replacement.  Led to bad reference count for both
the existing value and its replacement
- Missing reference count increment in noit_check_add_to_list
when inserting into the skip list
- Return noit_check_t* from noit_poller_check_found_and_backdated
- Don't assume vcheck stays null in noit_poller_check_found_and_backdated
- Optimize noit_poller_process_checks so it depends on the return
valie of mtev_skiplist_insert to avoid atomics
- Introduce watchlist_lock to avoid races in-between mtev_skiplist_find and
possibly removing the value before its reference count is incremented
- …
=> CIRC-6926 - Bad Ref Cnt

src/modules/snmp.c
Make sure checks are distinct before incrementing
=> CIRC-6993 - Verify Distinct SNMP Checks before Increment

src/noit_metric_tag_search.c, test/test_tags.c
* Allow spaces
* Treat // as a greedier match (allowing for more reserved characters)
* Allow for "<escaped string>" as an alternative b"<encoded string>"
=> Make metric serarch parsing more flexible.

src/noit_metric_tag_search.c, src/noit_metric_tag_search.h
These fields are not modified, so we should flag them as const.
=> CIRC-7654 - Make Const Things Const In Tag Search

src/noit_metric_tag_search.c, src/noit_metric_tag_search.h
The search passed to noit_metric_tag_search_unparse is not modified; it
should be passed in as a const.
=> Argument To noit_metric_tag_search_unparse Should Be const

src/noit_metric_tag_search.c, src/noit_metric_tag_search.h, test/test_tags.c
Added a function to noit_metric_tag_search that will allow taking any
two elements in a list and having them swap places.
=> Add Tag Search Swap Function

src/noit_metric_tag_search.c
tag search 're' expressions that don't compile should not crash the
matcher.
=> Make invlid regular expressions safe.

src/flatbuffers/filterset_rule.fbs, src/modules/histogram.c, src/noit_check_rest.c, src/noit_conf_checks.c, src/noit_filters.c, src/noit_filters.h, src/noit_filters_lmdb.c, src/noit_metric.c, test/busted/cluster/filters/filter_spec.lua, test/busted/simple/filters/filter_spec.lua
Add a new filterrule type, `add_measurement_tag:<tag>:<cat>`, that will apply a measurement tag and move on to the next rule in the filterset if it is encountered.
=> Add Filterrule Type To Apply Measurement Tags

src/modules/httptrap.c, src/noit_filters.c
Two quick changes:
* Fix httptrap module to use newly allocated memory after applying
filtersets
* Don't apply measurement tags for histograms or METRIC_GUESS
metrics - these are tricky and need more care before they're ready.
=> HTTPTrap And Histogram Measurement Tag Fixes

src/noit_metric.h
Save 14 bytes per ``metric_t``
=> CIRC-8356 - pack metric_t

src/noit_message_decoder.c
Replace an assert with a mtevFatal that gives details about the cause of
the failure.
=> Add Debug Information When Message Decode Fails

src/noit_metric_director.c
Allows for having the config in an included file, rather than
exactly one level deep.
=> Fix XPath for finding metric_director cache config

src/modules/histogram.c, src/modules/httptrap.c, src/modules/prometheus.c, src/noit_check.c, src/noit_metric.c, src/noit_metric.h, src/noit_socket_listener.c
When using ``noit_stats_mark_metric_logged`` it takes ownership of the passed
in ``metric_t`` pointer.  This creates a race between the 3 updated call sites
clearing, and freeing, their hash table versus the one found inside
``noit_stats``
Harmonize everything with ownership under ``noit_stats`` and the call sites
respecting that
- Remove call to ``noit_check_get_stats_current``, return value is not used
- Consolidate ``metric_local_free`` code
- Only use SMR to allocate ``metric_t``
- ``immediate_metrics`` does not own anything, do not delete from there
- Add a couple of ``default`` clauses, Eclipse paints the entire switch
statement in yellow otherwise
=> CIRC-8777 - use after free

src/noit_message_decoder.c, src/noit_metric.c, src/noit_metric.h
Add a callback function (wrapped in a context struct for ease of later
expansion) to allow passing a custom validation function to drop certain
tags when doing tag compaction.
=> Add Validation Callback To Tagset Compaction

src/noit_check_lmdb.c, src/noit_filters_lmdb.c, src/noit_lmdb_tools.c, src/noit_lmdb_tools.h
Rather than checking to see if we're using at least 80% of the LMDB
map, use generations to determine whether another thread has resized or
not.
=> Use Generations To Determine If Resizes Are Needed

src/noit_lmdb_tools.c
* Use a starting map size aligned with pagesize that is at least 64MB
* Resize DBs by a factor of 4
* Improve resize print messages
=> LMDB Tweaks

src/noit_check_rest.c, src/noitd.c
The checks/updates functionality grabs a lock and can iterate a lot of checks and build a large XML document. Should do this work in a jobq.
=> Pull Check Updates In Jobq

src/noit_metric_tag_search.c, src/noit_metric_tag_search.h, test/test_tags.c
Add parse_lazy and clone_lazy functions to avoid PCRE compilation during
parsing.  Do not study PCREs by default, track executions and once we
have 50 calls to pcre_exec then study the PCRE.  Rework the lfu such
that the token is tracked with the returned object and is released once
the node is freed.
CIRC-8958
=> compile and study search AST on-demand.

src/noit_check_rest.c, src/noit_filters.c
Fix two issues: One where we acquire a read lock and never release it in
an error case, and one where we acquired a read lock, but release a
write lock.
=> Fix Bad mtev_conf Lock Acquisition

src/noit_check_log.c, src/noit_metric_tag_search.c
Somehow a null pointer got into the current stats hash table.
Don't crash when it does happen
=> CIRC-9039 - null metric

src/noit_check_log.c, src/noit_filters.c
If we get a null metric when trying to log or filter, just skip it.
=> Better Null Metric Handling

src/noit_metric_tag_search.c, src/noit_metric_tag_search.h
Add noit_metric_tag_search_unparse_limit_size, which allows setting a
size limit to ensure that we don't go overboard with extremely large
queries.
Limit recursion to make sure we don't blow out the stack.
=> Add Size-Limited Noit Metric Find Unparse Function

src/noit_filters_rest.c, src/noitd.c
This task takes a lock, which could result in blocking the main eventer thread. This should go into a separate jobq.
=> Put Filter Updates In Separate Jobq

src/noit_check.c, src/noit_clustering.c, src/noit_clustering.h
When the check recycler is seeing if a delete is pending, it grabs a lock that can potentially freeze things up. Rather than taking the lock, we should only attempt to get it, and if it fails, we should go back and try again later.
=> Use Trylock When Checking If Delete Is Pending

src/noit_check.c, src/noitd.c
This process can take a long time and is currently on the main thread, which can cause things to block or watchdog. It is not time time-sensitive task, so we should move it into a jobq to keep the main thread clear.
=> Move Check Recycler Into A Jobq

src/modules/noit_lua_libnoit_binding.c, src/modules/noit_lua_noit_binding.c, src/noit_filters_rest.c, src/noitd.c
Make both the lua filterset cull integration and REST API filterset cull endpoint do their work in a jobq to keep large operations from blocking the eventer thread.
=> Do Filterset Culls In Jobq

src/noit_message_decoder.c, test/test_tags.c
`noit_metric_tagset_builder_add_many` needs access to `tag.total_size` to correctly iterate through `tagstr`. 
this fixes a bug where, when a `tagnm` was `toolong` the `total_size` was not being set and would result in an overflow when trying to subtract an unknown value from the `size_t tagstr_len` which is unsigned. 
add test for tag pairs that are too long.
in the test file, I made `Matches` a structure definition to prevent merge conflicts when I add the implicit tag testing that uses the same struct.
=> CIRC-9495 - fix handling of tags that are too long

src/modules/resolver_cache.c, src/noit_check_resolver.c
Set an upper limit of 3600 seconds for DNS record TTLs. Checksum the serialized records to prevent reading back in bad data.
CIRC-9641
=> Protect against ludicrous TTLs in cache.

src/noit_metric_tag_search.c
=> Fix oversized memcpy in graphite brace expansion.

src/modules/httptrap.c
In the httptrap module, if a metric is given as a JSON object but there's only a single value, we should use the original type. Previously, we converted all incoming values to doubles.
=> Fix Computed Value When Only One Value Present

src/modules/httptrap.c
Use %.15e instead of %g to create double strings in the httptrap module. This will give the values far more precision.
=> More Precise httptrap Doubles

src/modules/httptrap.c, test/busted/checks_data/httptrap/httptrap_spec.lua, test/busted/checks_data/httptrap_synch/httptrap_synch_spec.lua
We were losing the original data type in httptrap checks in situations where we didn't need to.
Fix this so that if a complex type is provided, but there's only a single value, we preserve the type rather than converting it to a double.
=> Fix HTTPTRAP Data Type Loss

src/modules/httptrap.c
We don't strictly need this and there's performance/fanout issues associated with this. As it's not a large performance improvement, just remove this for now.
=> Revert httptrap ACO

BUILDING.md, THIRDPARTY-LIBS.md
Now need GCC 11 or other C++20 compiler.
Review and update system package list for EL7 and Ubuntu 20.04, and update third-party library build instructions.
=> Update build instructions

src/modules/otlphttp.cpp, src/modules/otlphttp.xml, test/busted/listener/otlphttp/otlphttp_scratch.lua
In testing of the broker with the enhanced otlphttp module, the default of grpc enabled and grpc ssl enabled causes a crash loop because grpc ssl is not configured properly (by the user).  In hindsight, we probably don't want port 4317 open by default, even if ssl were configured to some default.  And then we also don't want enabling grpc to result in immediate crash because ssl is enabled to try to protect the user from accidentally exposing unencrypted grpc port 4317 on the internet.
So...we just will make the default to disable grpc and disable grpc ssl, and let the user turn those on as they need/want them and on their own to configure them responsibly.
=> Make grpc disabled and grpc ssl disabled the default

src/modules/otlp.cpp
Found a bug in the code processing incoming integer metrics with a scale < 1, where it would scale the wrong variable and then pass the unscaled value across to be stored.
Also added a log message to a new default case so that we could see cases where the units is not recognized.
=> Fix scaling bug for numerics with scale < 1 and also add default case to catch unknown units types

src/modules/httptrap.c
When artificially limiting the amount of time spent reading in an eventer thread in the httptrap module, set the mask so that it will wake up and begin reading again as soon as possible.
=> Fix HttpTrap Read Resume Bug

src/noit_check_resolver.c
The noit_check_resolver_init() function was calling a function that could try to take a lock that the function already holds, leading to deadlock. Added a new, simple helper function to add the offending locking call to the event loop without calling it first, preventing the deadlock.
=> Fix Deadlock In Noit Check Resolver

src/modules/otlp.cpp, src/modules/otlpgrpc.cpp
Fix several memory leaks and places where hash tables were being used incorrectly. Also fix some issues where data points were being lost.
=> Fix OTLP/GRPC Module Memory Leaks/Misuses

src/modules/otlpgrpc.cpp
Need to call `mtev_memory_finish_thread` after handling the metric data.
=> Fix otlpgrpc Module Memory Leak

src/noit_check.c
We were checking the return on whether we marked a metric logged, but the function being called duplicates the metric if it needs it, so we need to unconditionally clean up.
=> Fix Memory Leak In Marking Metrics Logged

src/modules/prometheus.c
Fixed an issue where we could discard Prometheus metrics if:
* We have more than 1000 active metrics in a hash
or...
* We hit a metric name/timestamp collision
Fixed those bugs.
=> Fix Prometheus Module Discard Bug

src/noit_metric_director.c
Allow for reading from Kafka in noit metric director. For the moment, it assumes the data is in the same format.
=> Handle Kafka Data In Noit Metric Director

src/noit_check.c, src/noit_check_lmdb.c, src/noit_filters.c, src/noit_filters_lmdb.c
Added a check against the existing filtersets when doing cluster replication to make sure we're not blowing away more current data and to reduce the amount of unneeded work, which should speed up startup and reduce memory usage.
Also did various small bits of cleanup.
=> Improve LMDB Filter Processing Time And Cleanup

src/modules/prometheus.c, src/noit_metric_director.c, src/noit_prometheus_translation.c, src/noit_prometheus_translation.h
Pass around the tagged and untagged metric lengths so we properly set the values on incoming kafka/prometheus data.
=> Set Metric Lengths Properly In Prometheus Handling

src/noit_prometheus_translation.c
Prometheus sample timestamps are already in milliseconds, so we don't need to multiply by 1000.
=> Fix Prometheus Timestamp

src/noit_prometheus_translation.c
Fix bug where we were copying from a struct pointer instead of the actual name field.
=> Fix Broken Name In Histograms

src/noit_metric_director.c
Added the ability to dedupe prometheus metric messages. Since the remote_write endpoint lacks a timestamp, added a new method to dedupe messages based on parsed noit_metric messages to make this work.
=> Add Dedupe For Prometheus-Fomatted Data In Metric Director

src/noit_metric_tag_search.c
Witnessed this warning with gcc-13 on Ubuntu 24.04:
```
noit_metric_tag_search.c: In function 'graphite_expand_braces':
noit_metric_tag_search.c:460:52: error: '%s' directive output may be truncated writing up to 254 bytes into a region of size between 2 and 256 [-Werror=format-truncation=]
460 |       snprintf(prefix, MTEV_MAYBE_SIZE(prefix), "%s%s", pre, s);
|                                                    ^~
In file included from /usr/include/stdio.h:980,
from noit_metric_tag_search.c:41:
In function 'snprintf',
inlined from 'graphite_expand_braces' at noit_metric_tag_search.c:460:7:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:54:10: note: '__builtin___snprintf_chk' output between 1 and 509 bytes into a destination of size 256
54 |   return __builtin___snprintf_chk (__s, __n, …
```
=> SO-8180 Fix warning popped by gcc-13
